development:
  adapter: mysql
  username: root
  host:  localhost
  database: simple_lis_opensource_development

test:
  adapter: mysql
  username: root
  host:  localhost
  database: simple_lis_opensource_test

